project_id = "nlbnmsiqfywskuxhqjon"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.backfill-wallet-trustlines]
    verify_jwt = false
  [functions.daily-seed]
    verify_jwt = false
  [functions.federation]
    verify_jwt = false
  [functions.fetch-brh-rate]
    verify_jwt = false
  [functions.get-public-invoice]
    verify_jwt = false
  [functions.notify-admin]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.scheduled-tx]
    verify_jwt = false
  [functions.theo-api-ping]
    verify_jwt = false
  [functions.theo-api-wallets]
    verify_jwt = false
  [functions.theo-api-quote]
    verify_jwt = false
  [functions.theo-api-pay]
    verify_jwt = false
  [functions.theo-api-convert]
    verify_jwt = false
  [functions.theo-api-payments]
    verify_jwt = false
